legion/bikes_app/urls.py
from django.urls import path, include
from bikes_app import views

app_name = 'bikes_app'
urlpatterns = [
    path('', views.bikesHome, name='bikesHome'),
    path('<int:id>', views.bikeDetails, name='bikeDetails')
]

legion/legion/urls.py
from django.contrib import admin
from django.urls import path, include


app_name = 'legion'

urlpatterns = [
    path('bikes/', include('bikes_app.urls')),
    path('user/', include('user_app.urls')),
    path('main/', include('main_app.urls')),
    path('admin/', admin.site.urls),
]

legion/main_app/urls.py
from django.urls import path, include
from main_app import views

app_name = 'main_app'
urlpatterns = [
    path('contact_us', views.contactUs, name='contactUs'),
]

legion/user_app/urls.py
from django.urls import path, include
from user_app import views

app_name = 'user_app'
urlpatterns = [
    path('info', views.user_info, name='info'),
    path('login', views.user_login, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.user_logout, name='logout'),
]

legion/bikes_app/models.py
from django.db import models

# Create your models here.
class BikeManufacturers(models.Model):
    name = models.CharField(blank=False, max_length=100)

    def __str__(self):
        return self.name

class Bikes(models.Model):
    id = models.AutoField(primary_key=True)
    model = models.CharField(blank=True, max_length=255)
    manufacturer = models.ForeignKey(BikeManufacturers, on_delete=models.CASCADE)
    ex_showroom_price = models.CharField(blank=True, max_length=100)
    image_link = models.TextField(blank=True)
    engine_displacement = models.CharField(blank=True, max_length=100)
    variant = models.CharField(blank=True, max_length=255)
    def __str__(self):
        return "{} {} {}".format(self.manufacturer, self.model, self.variant)

class BikeDetails(models.Model):
    bike = models.OneToOneField(Bikes, on_delete=models.CASCADE)
    engine_type = models.CharField(blank=True, max_length=255)
    cooling_system = models.CharField(blank=True, max_length=100)
    power = models.CharField(blank=True, max_length=100)
    torque = models.CharField(blank=True, max_length=100)
    fuel_type = models.CharField(blank=True, max_length=50)
    wheels = models.CharField(blank=True, max_length=100)
    transmission = models.CharField(blank=True, max_length=100)
    no_of_gears = models.CharField(blank=True, max_length=100)
    brake_front = models.CharField(blank=True, max_length=100)
    brake_rear = models.CharField(blank=True, max_length=100)
    suspension_front = models.CharField(blank=True, max_length=255)
    suspension_rear = models.CharField(blank=True, max_length=255)
    body_type = models.CharField(blank=True, max_length=100)
    ABS = models.CharField(blank=True, max_length=100)
    console = models.CharField(blank=True, max_length=100)

    def __str__(self):
        return "{} {} {}".format(self.bike.manufacturer, self.bike.model, self.bike.variant)

legion/cars_app/models.py
from django.db import models

# Create your models here.

legion/main_app/models.py
from django.db import models

# Create your models here.

legion/user_app/models.py
from django.db import models
from django.contrib.auth.models import User
from bikes_app.models import Bikes
# Create your models here.

class Role(models.Model):
    name = models.CharField(blank=False, max_length=100)

    def __str__(self):
        return self.name

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    role = models.ForeignKey(Role, on_delete=models.CASCADE)

    first_name = models.CharField(blank=False, max_length=255)

    last_name = models.CharField(blank=False, max_length=255)

    owned_bike = models.ForeignKey(Bikes, on_delete=models.CASCADE, blank=True, null = True)

    owned_bike_review = models.TextField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return "{} {} {}".format(self.first_name, self.last_name, self.user.username)

legion/user_app/forms.py
from django import forms
from django.contrib.auth.models import User
from user_app.models import UserProfile

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta(object):
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('first_name', 'last_name','owned_bike', 'owned_bike_review','profile_pic')

legion/bikes_app/views.py
from django.shortcuts import render
from bikes_app.models import Bikes, BikeDetails
# Create your views here.

def bikesHome(request):
    bikes = Bikes.objects.all()
    bikes_dict = {'bikes':bikes}
    return render(request, 'bikes_app/bikes_home.html', context = bikes_dict)

def bikeDetails(request, id):
    # print(str(id))
    bike = Bikes.objects.get(id=id)
    # print(str(bike.variant))
    bikeDetails = BikeDetails.objects.get(bike=bike)
    # print(bikeDetails.engine_type)


    # bikes = Bikes.objects.all()
    # bikes_dict = {'bikes':bikes}
    return render(request, 'bikes_app/bike_details.html', {"bike_details":bikeDetails})

legion/cars_app/views.py
from django.shortcuts import render

# Create your views here.

legion/main_app/views.py
from django.shortcuts import render

# Create your views here.
def contactUs(request):
    return render(request, 'main_app/contact_us.html')

legion/user_app/views.py
from django.shortcuts import render
from user_app.forms import UserForm, UserProfileForm
from user_app.models import Role, UserProfile
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
# Create your views here.

def register(request):
    registered = False

    if request.method == 'POST':

        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            role = Role.objects.get(name='EVERYONE')
            profile.role = role

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES('profile_pic')

            profile.save()
            registered = True

        else:
            print("ERROR : {} {}".format(user_form.errors, profile_form.errors))

    else :
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'user_app/registration.html',
                  { 'user_form' : user_form,
                    'profile_form':profile_form,
                    'registered':registered})

def user_login(request):

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:

            if user.is_active:

                login(request, user)
                return HttpResponseRedirect(reverse('bikes_app:bikesHome'))

            else:
                return HttpResponse('Account not Active')

        else:
            print("INVALID CREDENTIALS : Username- {} and password- {}".format(username, password))
            return HttpResponse("INVALID LOGIN DETAILS SUPPLIED")

    else:
        return render(request, 'user_app/login.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('bikes_app:bikesHome'))

@login_required
def user_info(request):
    print("LOGGED IN USER : {}".format(request.user.username))
    logged_in_user = request.user.username
    user = User.objects.get(username=logged_in_user)
    profile = UserProfile.objects.get(user=user)
    return render(request, "user_app/user_info.html", {"user_profile":profile})

legion/templates/bikes_app/bike_details.html
<!DOCTYPE html>
{% extends "main_app/base.html" %}
  {% block body_block %}
  {% if bike_details %}

  <h1 class="container center">{{ bike_details.bike.manufacturer }} {{ bike_details.bike.model }} {{ bike_details.bike.variant}}</h1>
  <dl class="container row mx-auto">

    <dt class="col-sm-3">Price</dt>
    <dd class="col-sm-9">{{ bike_details.bike.ex_showroom_price }}</dd>

    <dt class="col-sm-3">Engine Type</dt>
    <dd class="col-sm-9">{{ bike_details.engine_type }}</dd>

    <dt class="col-sm-3">Engine Diplacement</dt>
    <dd class="col-sm-9">{{ bike_details.bike.engine_displacement }}</dd>

    <dt class="col-sm-3">Cooling System</dt>
    <dd class="col-sm-9">{{ bike_details.cooling_system }}</dd>

    <dt class="col-sm-3">Max Power</dt>
    <dd class="col-sm-9">{{ bike_details.power }}</dd>

    <dt class="col-sm-3">Max Torque</dt>
    <dd class="col-sm-9">{{ bike_details.torque }}</dd>

    <dt class="col-sm-3">Fuel Type</dt>
    <dd class="col-sm-9">{{ bike_details.fuel_type }}</dd>

    <dt class="col-sm-3">Wheel Type</dt>
    <dd class="col-sm-9">{{ bike_details.wheels }}</dd>

    {% if bike_details.transmission %}
      <dt class="col-sm-3">Transmission</dt>
      <dd class="col-sm-9">{{ bike_details.transmission }}</dd>
      {% if bike_details.transmission == "Manual" %}
        <dt class="col-sm-3">No of Gears</dt>
        <dd class="col-sm-9">{{ bike_details.no_of_gears }}</dd>
      {% endif %}
    {% endif %}

    <dt class="col-sm-3">Brake Front</dt>
    <dd class="col-sm-9">{{ bike_details.brake_front }}</dd>

    <dt class="col-sm-3">Brake Rear</dt>
    <dd class="col-sm-9">{{ bike_details.brake_rear }}</dd>

    <dt class="col-sm-3">Suspension Front</dt>
    <dd class="col-sm-9">{{ bike_details.suspension_front }}</dd>

    <dt class="col-sm-3">Suspension Rear</dt>
    <dd class="col-sm-9">{{ bike_details.suspension_rear }}</dd>

    <dt class="col-sm-3">Body Type</dt>
    <dd class="col-sm-9">{{ bike_details.body_type }}</dd>

    <dt class="col-sm-3">ABS</dt>
    <dd class="col-sm-9">{{ bike_details.ABS }}</dd>

    <dt class="col-sm-3">Console</dt>
    <dd class="col-sm-9">{{ bike_details.console }}</dd>
  </dl>

  {% else %}
    <p>BIKE Details NOT FOUND !!!</p>
    <p>Add Some bikes from Admin Page</p>
  {% endif %}
  {% endblock %}

legion/templates/bikes_app/bikes_home.html
<!DOCTYPE html>
{% extends "main_app/base.html" %}
  {% block body_block %}
  {% if bikes %}
    <div class="row row-cols-1 row-cols-md-3">
      {% for bike in bikes %}
      <div class="col mb-4">
          <div class="card">
            <img class="card-img-top" src= {{ bike.image_link }} alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title">{{ bike.model }} {{ bike.variant }}</h5>
              <table>
                <tr>
                  <td>{{ bike.manufacturer }}</td> <td>{{ bike.engine_displacement }}</td>
                </tr>
                <tr>
                  <td><span>Ex-Showroom price</span></td>
                </tr>
                <tr>
                  <td>{{bike.ex_showroom_price}}</td>
                </tr>
              </table>
              <a href="{% url 'bikes_app:bikeDetails' id=bike.id %}" class="btn btn-primary">Details >></a>
            </div>
            <div class="card-footer">
              <small class="text-muted">Get amazing Offers and extra discounts</small>
            </div>
          </div>
        </div>
      {% endfor %}
  {% else %}
    <p>BIKES NOT FOUND !!!</p>
    <p>Add Some bikes from Admin Page</p>
  {% endif %}
  {% endblock %}

legion/templates/main_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Legion Vehicles</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "/css/base.css" %}">
  </head>
  <body>
    <div class="container reduced_height">
      <img src="https://ricks-motorcycles.com/wp-content/uploads/2017/03/Pano1-3.jpg" alt="My Image" class="img-fluid" >
    </div>

    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Legion Bikes</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'bikes_app:bikesHome' %}">Bikes</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Cars</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Enquiry</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main_app:contactUs' %}">Contact Us</a>
            </li>
          </ul>
          {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'user_app:info' %}">Account</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'user_app:logout' %}">Logout</a>
              </li>
            </ul>
          {% else %}
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'user_app:register' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'user_app:login' %}">Login</a>
              </li>
            </ul>
          {% endif %}
        </div>
      </nav>
    </div>

    <div class="container">
      <br>
      {% block body_block %}

      {% endblock %}
    </div>
  </body>
</html>

legion/templates/main_app/contact_us.html
<!DOCTYPE html>
{% extends "main_app/base.html" %}
  {% block body_block %}
    <br><br>
    <div class="container">
      <blockquote class="blockquote">
        <p class="mb-0">Sometimes, you find yourself in the middle of nowhere; and sometimes, in the middle of nowhere, you find yourself</p>
        <footer class="blockquote-footer">Never stop !!!<cite title="Source Title">Legion Vehicles</cite></footer>
      </blockquote>
      <br><br>
      <p class="h1 text-center">Contact Us</p>
      <br>
      <p class="h3 text-center">Name : Swapnil Vaidya</p>
      <br>
      <p class="h3 text-center">Email : swapnil@legion.com</p>
      <br>
      <p class="h3 text-center">Contact Number : +91 00000000001</p>
    </div>

  {% endblock %}

legion/templates/user_app/login.html
{% extends "main_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>Please login</h1>
  <form action="{% url 'user_app:login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" value="Enter Username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">
  </form>
</div>

{% endblock %}

legion/templates/user_app/registration.html
{% extends "main_app/base.html" %}
{% load static %}

{% block body_block %}

<div class="jumbotron">
  {% if registered %}
    <h1>Thank you for registration</h1>
  {% else %}
      <h1>Register Here !!!</h1>
      <h3>Fill out form : </h3>

      <form encrypt="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register">
      </form>
  {% endif %}

</div>
{% endblock %}

legion/templates/user_app/user_info.html
{% extends "main_app/base.html" %}
{% block body_block %}

<div class="jumbotron">

  <img src="https://imagevars.gulfnews.com/2020/01/22/Hrithik-Roshan--3--1579703264814_16fcda6e62f_large.jpg class="rounded mx-auto d-block" ">
  <h1>Hi {{ user_profile.first_name }} {{ user_profile.last_name }}</h1>
</div>
<div class="container">
  <dl class="container row mx-auto">

    <dt class="col-sm-3">Email</dt>
    <dd class="col-sm-9">{{ user_profile.user.email }}</dd>

    <dt class="col-sm-3">Username</dt>
    <dd class="col-sm-9">{{ user_profile.user.username }}</dd>

    <dt class="col-sm-3">First name</dt>
    <dd class="col-sm-9">{{ user_profile.first_name }}</dd>

    <dt class="col-sm-3">Last name</dt>
    <dd class="col-sm-9">{{ user_profile.last_name }}</dd>

  </dl>
</div>
{% endblock %}